// src/nuxt/pages/about.vue
<template>
    
    <div class="lg:w-[600px] mx-auto">
        <div class="p-8">
            <h2 class="text-4xl">What is Lorem Ipsum?</h2>
            <hr class="mb-4">
            <p>                
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
    </div>

</template>

// src/nextjs/src/pages/about.tsx
const About = () => {
    return (
        <>
            <div className="w-[90%] md:w-[600px] mx-auto">
                <div className="p-8 flex flex-col flex-wrap">
                    <h1 className="text-4xl">About</h1>
                    <hr className="h-[4px] bg-gray-400 mb-4"/>
                    <p>
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
                </div>
            </div>
        </>
    )    
}



export default About
